//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USAV_Solicitudes
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatLocalidades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatLocalidades()
        {
            this.TblCalendario = new HashSet<TblCalendario>();
        }
    
        public int IdLocalidad { get; set; }
        public string DescLocalidades { get; set; }
        public Nullable<int> IdEdificio { get; set; }
        public Nullable<int> IdTipoBloque { get; set; }
        public Nullable<int> IdConfigLaboral { get; set; }
        public string Pict { get; set; }
    
        public virtual CatEdificios CatEdificios { get; set; }
        public virtual CatTipoBloques CatTipoBloques { get; set; }
        public virtual TblConfiguracionLaboral TblConfiguracionLaboral { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCalendario> TblCalendario { get; set; }
    }
}
