//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USAV_Solicitudes
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatTipoBloques
    {
        public CatTipoBloques()
        {
            this.CatLocalidades = new HashSet<CatLocalidades>();
        }
    
        public int IdTipoBloque { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> DuracionM { get; set; }
    
        public virtual ICollection<CatLocalidades> CatLocalidades { get; set; }
    }
}
