//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USAV_Solicitudes
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatTipoReserva
    {
        public CatTipoReserva()
        {
            this.TblReservas = new HashSet<TblReservas>();
        }
    
        public int IdTipoReserva { get; set; }
        public string DescTipoReserva { get; set; }
    
        public virtual ICollection<TblReservas> TblReservas { get; set; }
    }
}
