//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USAV_Solicitudes
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAuditoria
    {
        public int Id { get; set; }
        public string Ip { get; set; }
        public string Navegador { get; set; }
        public Nullable<System.DateTime> FechaVisita { get; set; }
        public string RutaAcceso { get; set; }
        public string AccionRealizada { get; set; }
        public string NombreUsuario { get; set; }
    }
}
