//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USAV_Solicitudes
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblArticulos
    {
        public int IdArticulo { get; set; }
        public string TituloArticulo { get; set; }
        public string ContenidoArticulo { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<bool> Publicado { get; set; }
        public Nullable<bool> Destacado { get; set; }
        public Nullable<int> IdCatArticulo { get; set; }
        public Nullable<System.DateTime> FechaPublicacion { get; set; }
    
        public virtual TblCategoriasArticulos TblCategoriasArticulos { get; set; }
    }
}
