//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USAV_Solicitudes
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCreadorVideos
    {
        public TblCreadorVideos()
        {
            this.TblReservas = new HashSet<TblReservas>();
            this.TblVideos = new HashSet<TblVideos>();
        }
    
        public int IdCreadorVideo { get; set; }
        public string RutaImagenDocente { get; set; }
        public string Nombres { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
        public string Informacion { get; set; }
        public string Espcialidad { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string Sexo { get; set; }
        public string Cedula { get; set; }
        public string Usuario { get; set; }
        public string Email { get; set; }
        public Nullable<int> IdVideo { get; set; }
    
        public virtual ICollection<TblReservas> TblReservas { get; set; }
        public virtual ICollection<TblVideos> TblVideos { get; set; }
    }
}
