//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USAV_Solicitudes
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCalendario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblCalendario()
        {
            this.TblReservaLocalidad = new HashSet<TblReservaLocalidad>();
        }
    
        public int IdCalendario { get; set; }
        public string DescCalendario { get; set; }
        public Nullable<int> IdLocalidad { get; set; }
        public Nullable<System.DateTime> FechaCalendario { get; set; }
        public Nullable<int> Hora { get; set; }
        public Nullable<int> Minuto { get; set; }
        public Nullable<int> DuracionM { get; set; }
    
        public virtual CatLocalidades CatLocalidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblReservaLocalidad> TblReservaLocalidad { get; set; }
    }
}
