//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USAV_Solicitudes
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblComentarios
    {
        public int IdComentario { get; set; }
        public Nullable<int> Votacion { get; set; }
        public string Comentario { get; set; }
        public Nullable<System.DateTime> FechaComentario { get; set; }
        public string UserName { get; set; }
        public string TipoComentario { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<int> IdComentado { get; set; }
    }
}
