//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USAV_Solicitudes
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCurso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblCurso()
        {
            this.TblBloqueCurso = new HashSet<TblBloqueCurso>();
            this.TblMatriculadosCursos = new HashSet<TblMatriculadosCursos>();
        }
    
        public int IdCurso { get; set; }
        public string NombreCurso { get; set; }
        public string RutaImagenCurso { get; set; }
        public Nullable<System.TimeSpan> DuracionCurso { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<int> IdCatCurso { get; set; }
        public Nullable<int> IdNivelCurso { get; set; }
        public string PassCurso { get; set; }
        public string ResumenCurso { get; set; }
        public Nullable<bool> Privado { get; set; }
        public Nullable<int> IdCreadorVideo { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<bool> Finalizado { get; set; }
        public Nullable<int> NumVisitas { get; set; }
        public Nullable<bool> Bajar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblBloqueCurso> TblBloqueCurso { get; set; }
        public virtual TblCategoriaCurso TblCategoriaCurso { get; set; }
        public virtual TblNivelCurso TblNivelCurso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMatriculadosCursos> TblMatriculadosCursos { get; set; }
    }
}
