//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USAV_Solicitudes
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCategoriasArticulos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblCategoriasArticulos()
        {
            this.TblArticulos = new HashSet<TblArticulos>();
        }
    
        public int IdCatArticulo { get; set; }
        public string NombreCatArticulo { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblArticulos> TblArticulos { get; set; }
    }
}
