//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USAV_Solicitudes
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblConfiguracionLaboral
    {
        public TblConfiguracionLaboral()
        {
            this.CatLocalidades = new HashSet<CatLocalidades>();
        }
    
        public int IdConfigLababoral { get; set; }
        public Nullable<int> HorasLaborales { get; set; }
        public string DiaInicial { get; set; }
        public string DiaFinal { get; set; }
        public Nullable<int> DiasLaborales { get; set; }
        public string HorasAlmuerzo { get; set; }
        public string HoraInicialLaboral { get; set; }
        public string HoraFinalLaboral { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<CatLocalidades> CatLocalidades { get; set; }
    }
}
