//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USAV_Solicitudes
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblConfiguraciones
    {
        public int IdConf { get; set; }
        public string RutaVideos { get; set; }
        public string UserYoutube { get; set; }
        public string PassYoutube { get; set; }
        public string KeyDev { get; set; }
        public Nullable<int> IdUltimosVideo { get; set; }
        public string NombreApliacion { get; set; }
        public Nullable<int> IdArticuloServicios { get; set; }
        public Nullable<int> IdCatArticuloPrincipal { get; set; }
        public Nullable<int> IdCatArticuloAyuda { get; set; }
        public Nullable<int> IdTipoVideoCurso { get; set; }
    }
}
