//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USAV_Solicitudes
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblReservaLocalidad
    {
        public int IdReserva { get; set; }
        public int IdCalendario { get; set; }
        public int IdReservaLocalidad { get; set; }
    
        public virtual TblCalendario TblCalendario { get; set; }
        public virtual TblReservas TblReservas { get; set; }
    }
}
