//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USAV_Solicitudes
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUsuario
    {
        public int Carnet { get; set; }
        public string Nombres { get; set; }
        public string RutaFotoUsuario { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string NombreUsuario { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string CodigoSexo { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> FechaNac { get; set; }
        public string Acercademi { get; set; }
        public string Ciudad { get; set; }
    }
}
