//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USAV_Solicitudes
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblVideos
    {
        public int Id { get; set; }
        public string NombreVideo { get; set; }
        public Nullable<System.TimeSpan> DuracionVideo { get; set; }
        public string IdYoutube { get; set; }
        public Nullable<int> IdTipoVideo { get; set; }
        public string RutaVideo { get; set; }
        public Nullable<int> NumVistas { get; set; }
        public Nullable<System.DateTime> FechaSubida { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string Descripcion { get; set; }
        public string FormatoVideo { get; set; }
        public Nullable<double> PesoVideo { get; set; }
        public Nullable<int> IdBloque { get; set; }
        public Nullable<bool> PublicadoVideo { get; set; }
        public string CodNombreVideo { get; set; }
        public Nullable<bool> Visible { get; set; }
        public Nullable<int> IdSubCategoria { get; set; }
        public string Dimensiones { get; set; }
        public string CategoriasYoutube { get; set; }
        public string PalabrasYoutube { get; set; }
        public Nullable<bool> PrivacidadYoutubeVideo { get; set; }
        public Nullable<int> IdCreadorVideo { get; set; }
        public Nullable<bool> IsCurso { get; set; }
        public Nullable<bool> IsVideoPrincipalCurso { get; set; }
        public Nullable<int> NumVideo { get; set; }
        public string Photo { get; set; }
    
        public virtual TblBloqueCurso TblBloqueCurso { get; set; }
        public virtual TblCreadorVideos TblCreadorVideos { get; set; }
        public virtual TblSubCategorias TblSubCategorias { get; set; }
        public virtual TblTiposVideos TblTiposVideos { get; set; }
    }
}
