//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USAV_Solicitudes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class BDVideosUSAVEntitiesModelSolicitudes : DbContext
    {
        public BDVideosUSAVEntitiesModelSolicitudes()
            : base("name=BDVideosUSAVEntitiesModelSolicitudes")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CatEdificios> CatEdificios { get; set; }
        public DbSet<CatTipoReserva> CatTipoReserva { get; set; }
        public DbSet<TblReservaLocalidad> TblReservaLocalidad { get; set; }
        public DbSet<TblReservas> TblReservas { get; set; }
        public DbSet<CatTipoBloques> CatTipoBloques { get; set; }
        public DbSet<TblConfiguracionLaboral> TblConfiguracionLaboral { get; set; }
        public DbSet<VistaLocalidadCalendario> VistaLocalidadCalendario { get; set; }
        public DbSet<ViewReservasLoc> ViewReservasLoc { get; set; }
        public DbSet<TblCreadorVideos> TblCreadorVideos { get; set; }
        public DbSet<VIEW_ESTADISTICAS_TIPORESERVACION> VIEW_ESTADISTICAS_TIPORESERVACION { get; set; }
        public DbSet<VistaCursosCreados> VistaCursosCreados { get; set; }
        public DbSet<VistaReporteVideos> VistaReporteVideos { get; set; }
        public DbSet<TblCalendario> TblCalendario { get; set; }
        public DbSet<CatLocalidades> CatLocalidades { get; set; }
        public DbSet<TblVideos> TblVideos { get; set; }
        public DbSet<TblArticulos> TblArticulos { get; set; }
    
        public virtual ObjectResult<USP_DetalleSolicitud_Result> USP_DetalleSolicitud(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_DetalleSolicitud_Result>("USP_DetalleSolicitud", iDParameter);
        }
    
        public virtual ObjectResult<USP_DetalleS_Result> USP_DetalleS(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_DetalleS_Result>("USP_DetalleS", iDParameter);
        }
    
        public virtual ObjectResult<CARGAR_CANTRESERVAS_XFECHA_Result> CARGAR_CANTRESERVAS_XFECHA(Nullable<System.DateTime> fECHA1, Nullable<System.DateTime> fECHA2)
        {
            var fECHA1Parameter = fECHA1.HasValue ?
                new ObjectParameter("FECHA1", fECHA1) :
                new ObjectParameter("FECHA1", typeof(System.DateTime));
    
            var fECHA2Parameter = fECHA2.HasValue ?
                new ObjectParameter("FECHA2", fECHA2) :
                new ObjectParameter("FECHA2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CARGAR_CANTRESERVAS_XFECHA_Result>("CARGAR_CANTRESERVAS_XFECHA", fECHA1Parameter, fECHA2Parameter);
        }
    }
}
