//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USAV_Solicitudes
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_ESTADISTICAS_TIPORESERVACION
    {
        public int IdReserva { get; set; }
        public string DescLocalidades { get; set; }
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
        public string DescTipoReserva { get; set; }
        public string NombreSolicitante { get; set; }
        public string NombreInstitucion { get; set; }
        public string DescReserva { get; set; }
        public Nullable<int> DuracionMT { get; set; }
    }
}
