//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USAV_Solicitudes
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaReporteVideos
    {
        public int Id { get; set; }
        public string NombreVideo { get; set; }
        public Nullable<System.DateTime> FechaSubida { get; set; }
        public string NombretipoVideo { get; set; }
        public string NombreSubcategoria { get; set; }
        public string NombreDocente { get; set; }
    }
}
