//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USAV_Solicitudes
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaLocalidadCalendario
    {
        public int IdCalendario { get; set; }
        public Nullable<System.DateTime> FechaCalendario { get; set; }
        public string FechaCal { get; set; }
        public string hora { get; set; }
        public Nullable<int> IdLocalidad { get; set; }
        public Nullable<bool> Confirmacion { get; set; }
    }
}
